/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
  *********************************************************************************************************************/
 /*\title TC375 FreeRTOS basic example
 * \abstract This example shows how to get started with using the AURIX(TM) FreeRTOS port
 * \description This example explores FreeRTOS usage on AURIX(TM) TC375 using two simple tasks and one interrupt
 *
 * \name iLLD_TC375_ADS_FreeRTOS_Basic
 * \version V1.0.0
 * \board AURIX TC375 lite Kit, KIT_A2G_TC375_LITE, TC37xTP_A-Step
 * \keywords AURIX, TC3XX, TC375, FreeRTOS, Blinky, Task, ERU, LED, Button, External Interrupt
 * \documents See README.md
 * \lastUpdated 2023-04-27
 *********************************************************************************************************************/
#include <Drivers.h> // 새로운 BSP 초기화 헤더 파일

#include "FreeRTOS.h"
#include "task.h"

// 새로운 애플리케이션 태스크들을 위한 헤더 파일
#include "App/include/can_task.h"
#include "App/include/parking_task.h"
#include "App/include/button_motor_task.h" // 버튼 모터 제어 태스크 헤더 파일 추가
// 필요에 따라 다른 태스크 헤더 파일 추가
#include "App_Config.h"
#include "encoder_task.h"
#include "App/include/ultrasonic_task.h"
#include "App/include/aeb_task.h"

//IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;

void core0_main(void)
{
    // BSP 초기화 함수 호출
    System_Init();

    // [TEMP] Raspberry Pi 없이 테스트하기 위해 모터를 기본값으로 설정
//    Motor_Set_Left(1, 100);  // 정방향, 100 PWM
//    Motor_Set_Right(1, 100); // 정방향, 100 PWM

    // 기존 FreeRTOS 예제 태스크 생성 코드
//    xTaskCreate(task_app_led1, "APP LED1", configMINIMAL_STACK_SIZE, NULL, 0, NULL);
//    xTaskCreate(task_app_led2, "APP LED2", configMINIMAL_STACK_SIZE, NULL, 0, NULL);

    // 새로운 FreeRTOS 태스크 생성
    xTaskCreate(vCanMessageHandlerTask, "CAN Handler", configMINIMAL_STACK_SIZE * 2, NULL, 1, NULL);
    xTaskCreate(vAutonomousParkingTask, "Parking", configMINIMAL_STACK_SIZE * 4, NULL, 1, NULL);
//    xTaskCreate(vButtonMotorControlTask, "Button Motor", configMINIMAL_STACK_SIZE * 2, NULL, 1, NULL);
    // 필요에 따라 다른 태스크들도 여기에 추가
    xTaskCreate(vEncoderProcessingTask, "Encoder Task", configMINIMAL_STACK_SIZE, NULL, 1, NULL);
    xTaskCreate(vUltrasonicProcessingTask, "Ultrasonic", configMINIMAL_STACK_SIZE * 2, NULL, 2, NULL);
    xTaskCreate(vUltrasonicTriggerTask, "Ultrasonic Trig", configMINIMAL_STACK_SIZE, NULL, 3, NULL);
    xTaskCreate(vAebTask, "AEB Task", configMINIMAL_STACK_SIZE, NULL, 3, NULL);

    /* Start the scheduler */
    vTaskStartScheduler();

    // 스케줄러가 시작되면 이 루프는 실행되지 않습니다.
    while (1)
    {
    }
}

/* Required FreeRTOS callback, called in case of a stack overflow.
 * For the sake of simplicity, this function will loop indefinitely
 * and the root cause can be confirmed by using a debugger
 */
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    while (1)
    {
        __nop();
    }
}
